# -*- coding: utf-8 -*-
"""inventory_optimization_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Neha333-gif/tasks_ml/blob/main/inventory_optimization_system.ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, precision_recall_curve, auc
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from imblearn.over_sampling import SMOTE

import warnings
warnings.filterwarnings("ignore")


df = pd.read_csv("/content/grocery_chain_data.csv")

print(f" dataframe head : {df.head()}")
print(f" dataframe shape : {df.shape}")
print(f" dataframe info : {df.info()}")

y = df['final_amount']
df.drop(['customer_id', 'transaction_date', 'total_amount', 'discount_amount', 'final_amount'], axis = 1, inplace = True)
x = df
x_train, x_test, y_train, y_test = train_test_split(df, y, test_size=0.2, random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

for col in x.columns:
  if x[col].dtype == 'object':
    x[col] = LabelEncoder().fit_transform(x[col])
  else:
    x[col] = StandardScaler().fit_transform(x[col].values.reshape(-1, 1))

print(x)

from sklearn.preprocessing import LabelEncoder
import pandas as pd

# Make copies to avoid modifying the original x_train, x_test and SettingWithCopyWarning
x_train_processed = x_train.copy()
x_test_processed = x_test.copy()

# Identify and process object columns in x_train_processed and x_test_processed
for col in x_train_processed.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    x_train_processed[col] = le.fit_transform(x_train_processed[col])

    # Apply the same fitted encoder to the test set, handling unseen labels by mapping them to -1
    x_test_processed[col] = x_test_processed[col].map(lambda s: le.transform([s])[0] if s in le.classes_ else -1)
    # Ensure the column type is integer after transformation
    x_test_processed[col] = x_test_processed[col].astype(int)

xgb_model = xgb.XGBRegressor(
    n_estimators=500,
    max_depth=8,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    tree_method='hist',
    n_jobs=-1)

xgb_model.fit(x_train_processed, y_train)

y_pred = xgb_model.predict(x_test_processed)

from sklearn.metrics import mean_squared_error, r2_score
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"""
 MSE : {mse},
 R2 : {r2}
 """)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 7))
sns.scatterplot(x=y_test, y=y_pred, alpha=0.6)
plt.plot([min(y_test), max(y_test)], [min(y_test), max(y_test)], color='red', linestyle='--', lw=2)
plt.title('Actual vs. Predicted House Prices (Scaled)')
plt.xlabel('Actual Prices (Scaled)')
plt.ylabel('Predicted Prices (Scaled)')
plt.grid(True)
plt.show()

import joblib

joblib.dump(xgb_model, "xg boost model")
print("Model saved as xg boost ")