# -*- coding: utf-8 -*-
"""employee_attribution_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Neha333-gif/tasks_ml/blob/main/employee_attribution_model.ipynb
"""

from graphviz import jupyter_integration
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    roc_auc_score)

import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, precision_recall_curve, auc
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from imblearn.over_sampling import SMOTE

import warnings
warnings.filterwarnings("ignore")


df = pd.read_csv(r"C:\Users\peepl\Downloads\cust_segmentation_zip\repo_for_demand_forecasting\MFG10YearTerminationData.csv")

# print the dataset

print(f" dataframe head : {df.head()}")
print(f" dataframe shape : {df.shape}")
print(f" dataframe info : {df.info()}")

# handling null values

print(f"null values : {df.isnull().sum()}")

print(f"columns : {df.columns}")

# xgboost model

neg_count = y_train.value_counts()[0]
pos_count = y_train.value_counts()[1]

scale_pos_weight = neg_count / pos_count

xgb_model = xgb.XGBClassifier(
    n_estimators=500,
    max_depth=8,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric='auc',
    tree_method='hist',
    n_jobs=-1,
    scale_pos_weight=scale_pos_weight)

xgb_model.fit(x_train, y_train)
y_pred = xgb_model.predict(x_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"""
accuracy : {accuracy}
precision : {precision}
recall : {recall}
f1_score : {f1}
""")

from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print(cm)
# generate confusion matrix code

plt.figure(figsize = (6,4))
sns.heatmap(confusion_matrix(y_test, y_pred), annot = True, fmt = 'd', cmap = 'Blues')
plt.title('Confusion Matrix')
plt.xlabel('Predicted Labels')
plt.ylabel('True Labels')
plt.show()

importance = xgb_model.feature_importances_

feature_importance = pd.DataFrame({'feature': x.columns, 'importance': importance})
print(feature_importance.sort_values(by = 'importance', ascending = False))


import joblib
joblib.dump(xgb_model, 'employee_attribution_model.pkl')
print(f"saved model as employee_attribution_model.pkl")