# -*- coding: utf-8 -*-
"""customer_segmentation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Neha333-gif/tasks_ml/blob/main/customer_segmentation.ipynb
"""

pip install imbalanced-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from imblearn.over_sampling import SMOTE

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score
from sklearn.ensemble import RandomForestClassifier

df = pd.read_csv("/content/Test.csv")
print(df)

df2 = pd.read_csv("/content/Train.csv")
print(df2)

df.update(df2)
print(df)

for col_name in df.columns:
  print(f"{col_name} : {df[col_name].dtype}")

le = LabelEncoder()
scaler = StandardScaler()

df["Var_1"] = df["Var_1"].apply(lambda x:1 if x == "Cat_6" else 0)

for col in df:
  if df[col].dtype == "object" and col != "Var_1":
    df[col] = le.fit_transform(df[col].astype(str))

print(df)

# df.drop('ID', axis = 1, inplace=True)


y = df['Var_1']
x = df.drop(['Var_1'], axis=1)

for col in x:
  if x[col].isnull().sum() > 0 and x[col].dtype != "object":
    x.fillna(x[col].mean(), inplace=True)
  else:
    imputer = SimpleImputer(strategy="most_frequent")
    df[col] = imputer.fit_transform(df[[col]]).ravel()

y.dtype

y

y.value_counts()

smote = SMOTE(random_state=42)
x_resampled, y_resampled = smote.fit_resample(x, y)

print("Original y_train value counts:")
print(y.value_counts())
print("\nResampled y_train value counts (after SMOTE):")
print(y_resampled.value_counts())

x_train, x_test, y_train, y_test = train_test_split(x_resampled, y_resampled, test_size=0.2, random_state=42)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score)

xgb_model = XGBClassifier(
   n_estimators=300,
    learning_rate=0.1,
    max_depth=5,

    random_state=42,
    n_jobs=-1,

    colsample_bytree=0.7,
    subsample=0.8,

    objective='binary:logistic'
    # tree_method='auto'
   )

xgb_model.fit(x_train, y_train)
y_pred = xgb_model.predict(x_test)

accuracy_scores = accuracy_score(y_test, y_pred)
precision_scores = precision_score(y_test, y_pred)
recall_scores = recall_score(y_test, y_pred)
f1_scores = f1_score(y_test, y_pred) # caluculate metrics considering class imbalance

print(f"""
Accuracy Score : {accuracy_scores}
Precision Score : {precision_scores}
Recall Score : {recall_scores}
F1 Score : {f1_scores} """)

# r2_score = r2_score(y_test, y_pred)
# mae = mean_absolute_error(y_test, y_pred)
# mse = mean_squared_error(y_test, y_pred)

# print(f"R2 Score: {r2_score}")
# print(f"Mean Absolute Error: {mae}")
# print(f"Mean Squared Error: {mse}")

y_train.value_counts()

y_test.value_counts()

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['shortlisted', 'no_shortlisted']) # Assuming binary classification for 'liked'
disp.plot(cmap=plt.cm.Blues)

plt.xlabel('predicted data')
plt.ylabel('actual claim data')
plt.title('Confusion Matrix')
plt.show()

import joblib
if joblib.dump(xgb_model, 'customer_segmentation.pkl'):
  print("model saved")