# -*- coding: utf-8 -*-
"""fake_news_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Neha333-gif/tasks_ml/blob/main/fake_news_detection.ipynb
"""

# pip install imbalanced-learn

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from imblearn.over_sampling import SMOTE

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score
from sklearn.ensemble import RandomForestClassifier

df1 = pd.read_csv("fake news detection dataset/fake.csv")
df1["news_status"] = "fake"
print(df1)

df2 = pd.read_csv("fake news detection dataset/true.csv")
df2["news_status"] = "True"
print(df2)

df1.update(df2)
print(df1)

for col_name in df1.columns:
  print(f"{col_name} : {df1[col_name].dtype}")

le = LabelEncoder()
scaler = StandardScaler()

for col in df1:
  if df1[col].dtype == "object" and col != "news_status":
    df1[col] = le.fit_transform(df1[col].astype(str))


df1['date'] = pd.to_datetime(df1['date'])

df1["news_status"] = df1.apply(lambda row: 1 if row["news_status"] == "True" else 0, axis=1)
print(df1)

df1.drop('date', axis = 1, inplace=True)


y = df1['news_status']
x = df1.drop(['news_status'], axis=1)

for col in df1:
  if df1[col].isnull().sum() > 0 and df1[col].dtype != "object":
    df1.fillna(df1[col].mean(), inplace=True)
  else:
    imputer = SimpleImputer(strategy="most_frequent")
    df1[col] = imputer.fit_transform(df1[[col]]).ravel()

df1['news_status'].dtype

df1['news_status']

y.value_counts()

smote = SMOTE(random_state=42)
x_resampled, y_resampled = smote.fit_resample(x, y)

print("Original y_train value counts:")
print(y.value_counts())
print("\nResampled y_train value counts (after SMOTE):")
print(y_resampled.value_counts())

x_train, x_test, y_train, y_test = train_test_split(x_resampled, y_resampled, test_size=0.2, random_state=42)

print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    ConfusionMatrixDisplay)

xgb_model = XGBClassifier(
   n_estimators=300,
    learning_rate=0.1,
    max_depth=5,

    random_state=42,
    n_jobs=-1,

    colsample_bytree=0.7,
    subsample=0.8,

    objective='binary:logistic'
    # tree_method='auto'
   )

xgb_model.fit(x_train, y_train)
y_pred = xgb_model.predict(x_test)

accuracy_scores = accuracy_score(y_test, y_pred)
precision_scores = precision_score(y_test, y_pred)
recall_scores = recall_score(y_test, y_pred)
f1_scores = f1_score(y_test, y_pred) # caluculate metrics considering class imbalance

print(f"""
Accuracy Score : {accuracy_scores}
Precision Score : {precision_scores}
Recall Score : {recall_scores}
F1 Score : {f1_scores} """)

# r2_score = r2_score(y_test, y_pred)
# mae = mean_absolute_error(y_test, y_pred)
# mse = mean_squared_error(y_test, y_pred)

# print(f"R2 Score: {r2_score}")
# print(f"Mean Absolute Error: {mae}")
# print(f"Mean Squared Error: {mse}")

y_train.value_counts()

y_test.value_counts()

print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['shortlisted', 'no_shortlisted']) # Assuming binary classification for 'liked'
disp.plot(cmap=plt.cm.Blues)

plt.xlabel('predicted data')
plt.ylabel('actual claim data')
plt.title('Confusion Matrix')
plt.savefig('confusion_matrix_colab.png')
plt.close()

import joblib
if joblib.dump(xgb_model, 'fake news detection.pkl'):
  print("model saved")