# -*- coding: utf-8 -*-
"""weather_forecasting_pipeline.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Neha333-gif/tasks_ml/blob/main/weather_forcast.ipynb
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    roc_auc_score
)

import xgboost as xgb
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, precision_recall_curve, auc
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from imblearn.over_sampling import SMOTE
from sklearn.impute import SimpleImputer

import warnings
warnings.filterwarnings("ignore")

DATA_PATH = "weather_forecasting_data/weather_forecast.csv"
if not os.path.exists(DATA_PATH):
    # Try backup path
    DATA_PATH = "weather_forecasting_data/weather_forecast_original.csv"

df = pd.read_csv(DATA_PATH)

print(f" dataframe head : \n{df.head()}")
print(f" dataframe shape : {df.shape}")
print(f" dataframe info : \n")
df.info()

df['Play'] = LabelEncoder().fit_transform(df['Play'])
y = df['Play']

# Drop columns not used as features for training in basic script
drop_cols = [c for c in ['Play', 'Date'] if c in df.columns]
x = df.drop(columns=drop_cols)

imputer = SimpleImputer(strategy='most_frequent')
x = pd.DataFrame(imputer.fit_transform(x), columns=x.columns)

for col in x.columns:
  if x[col].dtype == 'object':
    x[col] = LabelEncoder().fit_transform(x[col])
  else:
    x[col] = StandardScaler().fit_transform(x[col].values.reshape(-1, 1))

print(y.value_counts())

smote = SMOTE(random_state=42, k_neighbors=4) # Set k_neighbors to be less than or equal to the smallest class size - 1
x, y= smote.fit_resample(x, y)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

print(y.value_counts())

# Initialize XGBoost Classifier model (matching user's structure)
xgb_model = xgb.XGBClassifier(
    n_estimators=300,
    max_depth=7,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    tree_method='hist',
    n_jobs=-1,
    verbose = True)

# Train the model
xgb_model.fit(x_train, y_train)

# Make predictions on the test set
y_pred = xgb_model.predict(x_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')

print(f"Accuracy: {accuracy}")
print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1 Score: {f1}")

# Plotting actual vs. predicted values
plt.figure(figsize=(10, 7))
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', cbar=False)
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.savefig("results/confusion_matrix.png")
plt.close()

import joblib

joblib.dump(xgb_model, "weather_forecasting_model_xgb.joblib")
print("Model saved as weather_forecasting_model_xgb.joblib")
